from button import *

class card_objects:
    def __init__(self):
        self.red0a = card(0, 'red')
        self.red1a = card(1, 'red')
        self.red2a = card(2, 'red')
        self.red3a = card(3, 'red')
        self.red4a = card(4, 'red')
        self.red5a = card(5, 'red')
        self.red6a = card(6, 'red')
        self.red7a = card(7, 'red')
        self.red8a = card(8, 'red')
        self.red9a = card(9, 'red')
        self.reddraw2a = card('draw2', 'red')
        self.redreversea = card('reverse', 'red')
        self.redskipa = card('skip', 'red')

        self.red0b = card(0, 'red')
        self.red1b = card(1, 'red')
        self.red2b = card(2, 'red')
        self.red3b = card(3, 'red')
        self.red4b = card(4, 'red')
        self.red5b = card(5, 'red')
        self.red6b = card(6, 'red')
        self.red7b = card(7, 'red')
        self.red8b = card(8, 'red')
        self.red9b = card(9, 'red')
        self.reddraw2b = card('draw2', 'red')
        self.redreverseb = card('reverse', 'red')
        self.redskipb = card('skip', 'red')


        self.blue0a = card(0, 'blue')
        self.blue1a = card(1, 'blue')
        self.blue2a = card(2, 'blue')
        self.blue3a = card(3, 'blue')
        self.blue4a = card(4, 'blue')
        self.blue5a = card(5, 'blue')
        self.blue6a = card(6, 'blue')
        self.blue7a = card(7, 'blue')
        self.blue8a = card(8, 'blue')
        self.blue9a = card(9, 'blue')
        self.bluedraw2a = card('draw2', 'blue')
        self.bluereversea = card('reverse', 'blue')
        self.blueskipa = card('skip', 'blue')

        self.blue0b = card(0, 'blue')
        self.blue1b = card(1, 'blue')
        self.blue2b = card(2, 'blue')
        self.blue3b = card(3, 'blue')
        self.blue4b = card(4, 'blue')
        self.blue5b = card(5, 'blue')
        self.blue6b = card(6, 'blue')
        self.blue7b = card(7, 'blue')
        self.blue8b = card(8, 'blue')
        self.blue9b = card(9, 'blue')
        self.bluedraw2b = card('draw2', 'blue')
        self.bluereverseb = card('reverse', 'blue')
        self.blueskipb = card('skip', 'blue')


        self.green0a = card(0, 'green')
        self.green1a = card(1, 'green')
        self.green2a = card(2, 'green')
        self.green3a = card(3, 'green')
        self.green4a = card(4, 'green')
        self.green5a = card(5, 'green')
        self.green6a = card(6, 'green')
        self.green7a = card(7, 'green')
        self.green8a = card(8, 'green')
        self.green9a = card(9, 'green')
        self.greendraw2a = card('draw2', 'green')
        self.greenreversea = card('reverse', 'green')
        self.greenskipa = card('skip', 'green')

        self.green0b = card(0, 'green')
        self.green1b = card(1, 'green')
        self.green2b = card(2, 'green')
        self.green3b = card(3, 'green')
        self.green4b = card(4, 'green')
        self.green5b = card(5, 'green')
        self.green6b = card(6, 'green')
        self.green7b = card(7, 'green')
        self.green8b = card(8, 'green')
        self.green9b = card(9, 'green')
        self.greendraw2b = card('draw2', 'green')
        self.greenreverseb = card('reverse', 'green')
        self.greenskipb = card('skip', 'green')


        self.yellow0a = card(0, 'yellow')
        self.yellow1a = card(1, 'yellow')
        self.yellow2a = card(2, 'yellow')
        self.yellow3a = card(3, 'yellow')
        self.yellow4a = card(4, 'yellow')
        self.yellow5a = card(5, 'yellow')
        self.yellow6a = card(6, 'yellow')
        self.yellow7a = card(7, 'yellow')
        self.yellow8a = card(8, 'yellow')
        self.yellow9a = card(9, 'yellow')
        self.yellowdraw2a = card('draw2', 'yellow')
        self.yellowreversea = card('reverse', 'yellow')
        self.yellowskipa = card('skip', 'yellow')

        self.yellow0b = card(0, 'yellow')
        self.yellow1b = card(1, 'yellow')
        self.yellow2b = card(2, 'yellow')
        self.yellow3b = card(3, 'yellow')
        self.yellow4b = card(4, 'yellow')
        self.yellow5b = card(5, 'yellow')
        self.yellow6b = card(6, 'yellow')
        self.yellow7b = card(7, 'yellow')
        self.yellow8b = card(8, 'yellow')
        self.yellow9b = card(9, 'yellow')
        self.yellowdraw2b = card('draw2', 'yellow')
        self.yellowreverseb = card('reverse', 'yellow')
        self.yellowskipb = card('skip', 'yellow')


        self.wild1 = card('wildchange', '')
        self.wild2 = card('wildchange', '')
        self.wild3 = card('wildchange', '')
        self.wild4 = card('wildchange', '')

        self.wilddraw1 = card('wilddraw4', '')
        self.wilddraw2 = card('wilddraw4', '')
        self.wilddraw3 = card('wilddraw4', '')
        self.wilddraw4 = card('wilddraw4', '')
        